### ISSUE TITLE
NPE and HashKey conflict in Xmemcached module

### ISSUE THREAD

**Issue by awarrior** [datanucleus/datanucleus-cache#6]
**NPE:**
Xmemcached code does not pre-handle null id before get CachedPC. this will throw npe like below:

> NestedThrowablesStackTrace:
java.lang.NullPointerException
	at org.datanucleus.cache.xmemcached.XmemcachedLevel2Cache.getCacheKeyForId (XmemcachedLevel2Cache.java:208)
	at org.datanucleus.cache.xmemcached.XmemcachedLevel2Cache.get (XmemcachedLevel2Cache.java:163)
	at org.datanucleus.state.AbstractStateManager.updateLevel2CacheForFields (AbstractStateManager.java:992)
	at org.datanucleus.state.AbstractStateManager.loadFieldsInFetchPlan (AbstractStateManager.java:1097)
	at org.datanucleus.store.fieldmanager.LoadFieldManager.processPersistable (LoadFieldManager.java:68)
	at org.datanucleus.store.fieldmanager.LoadFieldManager.internalFetchObjectField (LoadFieldManager.java:113)
	at org.datanucleus.store.fieldmanager.AbstractFetchDepthFieldManager.fetchObjectField (AbstractFetchDepthFieldManager.java:114)
	at org.datanucleus.state.AbstractStateManager.replacingObjectField (AbstractStateManager.java:1590)
	at org.datanucleus.state.StateManagerImpl.replacingObjectField(StateManagerImpl.java:120)
	at org.apache.hadoop.hive.metastore.model.MColumnDescriptor.dnReplaceField (MColumnDescriptor.java)
	at org.apache.hadoop.hive.metastore.model.MColumnDescriptor.dnReplaceFields (MColumnDescriptor.java)
	at org.datanucleus.state.StateManagerImpl.replaceFields(StateManagerImpl.java:3109)
	at org.datanucleus.state.StateManagerImpl.replaceFields(StateManagerImpl.java:3136)
	at org.datanucleus.state.AbstractStateManager.loadFieldsInFetchPlan (AbstractStateManager.java:1096)

**HashKey conflict:**

Another problem is that `getCacheKeyForId` function may cause key conflict because of the use of hashcode function on `id.toString()`. In my realistic test, there are 10 conflicts in 100000 queries.

**Comment by andyjefferson** [comment]
Since you are the only person who sees this, and there is no testcase provided, then I suggest that you get the code and provide a PULL REQUEST, because nobody else will be, and certainly not with no information.

Oh, and that stack trace does not line up with any code I have, so you are also using something very old.

**Comment by andyjefferson** [comment]
Closing since no testcase provided, and no apparent willingness to develop a fix for whatever is being seen. Post back here with testcase and/or pull request as required and this can be reopened
